import { initializeApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { addDoc, collection, doc, getFirestore, limit, onSnapshot, orderBy, query, serverTimestamp, setDoc } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const app = initializeApp({apiKey:"AIzaSyDeuW583lgxl08k-DYDju7jQiZP2jVqUk4",authDomain:"kindred-507209.firebaseapp.com",projectId:"kindred-507209",storageBucket:"kindred-507209.firebasestorage.app",messagingSenderId:"459167088901",appId:"1:459167088901:web:c13b3aeaf9d6e41e9cf76c"});
const auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider(); provider.setCustomParameters({prompt:"select_account"});
const id=x=>document.getElementById(x);
function note(t){const e=id("toast");if(!e)return;e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2400)}
function fail(e){console.error(e);return e?.code==="auth/popup-closed-by-user"?"Sign-in was cancelled.":e?.code==="auth/popup-blocked"?"Please allow pop-ups and try again.":"Something went wrong. Please try again."}
async function user(){if(auth.currentUser)return auth.currentUser;note("Sign in with Google to continue.");return(await signInWithPopup(auth,provider)).user}
const sign=id("signin");if(sign)sign.onclick=async()=>{try{auth.currentUser?await signOut(auth):await signInWithPopup(auth,provider)}catch(e){note(fail(e))}};
onAuthStateChanged(auth,async u=>{if(!sign)return;if(!u){sign.textContent="G · Sign in";return}const first=(u.displayName||"Member").split(" ")[0];sign.textContent=first+" · Sign out";try{await setDoc(doc(db,"users",u.uid),{displayName:u.displayName||"Kindred member",email:u.email||"",photoURL:u.photoURL||"",lastLoginAt:serverTimestamp()},{merge:true});note("Welcome, "+first+"!")}catch(e){note(fail(e))}});
const story=id("storyForm");if(story)story.onsubmit=async e=>{e.preventDefault();const title=id("storyTitle").value.trim(),text=id("storyText").value.trim();if(title.length<3||text.length<20){note("Add a title and at least 20 characters.");return}try{const u=await user(),anonymous=story.querySelector("select").value==="Anonymous";await addDoc(collection(db,"stories"),{title,text,authorId:u.uid,authorName:anonymous?"Anonymous":(u.displayName||"Member").split(" ")[0],createdAt:serverTimestamp()});story.reset();note("Your story is published.")}catch(e){note(fail(e))}};
const post=id("addTopic");if(post)post.onclick=async()=>{const input=id("topicTitle"),title=input.value.trim();if(title.length<5){note("Write at least 5 characters.");return}try{const u=await user();await addDoc(collection(db,"forumTopics"),{title,authorId:u.uid,authorName:(u.displayName||"Member").split(" ")[0],replyCount:0,createdAt:serverTimestamp()});input.value="";note("Your topic is published.")}catch(e){note(fail(e))}};
const join=id("joinBtn");if(join)join.onclick=async()=>{try{const u=await user();await addDoc(collection(db,"joinRequests"),{userId:u.uid,groupTitle:id("resultTitle").textContent,city:id("city").value.trim(),status:"pending",createdAt:serverTimestamp()});join.textContent="Request sent";join.disabled=true;note("Your request was sent.")}catch(e){note(fail(e))}};
function storyCard(d){const a=document.createElement("article");a.className="story-card firebase-story";a.innerHTML="<div><small>COMMUNITY STORY</small><h3></h3><p></p><b></b></div>";a.querySelector("h3").textContent=d.title;a.querySelector("p").textContent=d.text;a.querySelector("b").textContent="— "+(d.authorName||"Member");story.parentElement.insertBefore(a,story)}
function topicCard(d){const a=document.createElement("article");a.className="topic firebase-topic";a.innerHTML='<span class="topic-icon">✨</span><div><strong></strong><span></span></div><span class="count"></span>';a.querySelector("strong").textContent=d.title;a.querySelector("div span").textContent=(d.authorName||"Member")+" · community topic";a.querySelector(".count").textContent=d.replyCount||0;id("forumList").prepend(a)}
if(story)onSnapshot(query(collection(db,"stories"),orderBy("createdAt","desc"),limit(20)),s=>{document.querySelectorAll(".firebase-story").forEach(x=>x.remove());s.docs.slice().reverse().forEach(x=>storyCard(x.data()))},console.error);
if(id("forumList"))onSnapshot(query(collection(db,"forumTopics"),orderBy("createdAt","desc"),limit(30)),s=>{document.querySelectorAll(".firebase-topic").forEach(x=>x.remove());s.docs.slice().reverse().forEach(x=>topicCard(x.data()))},console.error);

// Replace prototype modal links with crawlable, substantive pages.
const trustPages={about:"about.html",safety:"safety.html",privacy:"privacy.html",terms:"terms.html",contact:"contact.html"};
document.querySelectorAll("[data-page]").forEach(a=>{const p=a.dataset.page;if(trustPages[p]){a.href=trustPages[p];a.removeAttribute("data-page");a.onclick=null}});
const firstGuide=document.querySelector('.guide[data-guide="friends"]');if(firstGuide){firstGuide.onclick=()=>location.href="guides/how-to-make-friends-in-a-new-city.html";firstGuide.setAttribute("aria-label","Read How to make friends in a new city")}
